In [35]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [36]:
dfx = pd.read_csv("../Datasets/Logistic_Data/logisticX.csv")
dfy = pd.read_csv("../Datasets/Logistic_Data/logisticY.csv")

In [37]:
dfx.head()


3.8915  4.2105
0  3.6898  6.6051
1  2.7763  7.5057
2  3.1137  5.7724
3  2.9251  5.4315
4  3.6699  6.4406

In [38]:
x = dfx.values
y = dfy.values

In [39]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state=0)

In [40]:
print(x_train.shape,y_train.shape)
print(x_test.shape,y_test.shape)
y_train = y_train.reshape(79,)
y_test = y_test.reshape(20,)
print(x_train.shape,y_train.shape)
print(x_test.shape,y_test.shape)

(79, 2) (79, 1)
(20, 2) (20, 1)
(79, 2) (79,)
(20, 2) (20,)


In [41]:
from sklearn.linear_model import LogisticRegression

In [42]:
logisticRegr = LogisticRegression()

In [43]:
logisticRegr.fit(x_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [44]:
y_test_model_pred = logisticRegr.predict(x_test)

In [45]:
print(y_test_model_pred)

[0 1 0 0 1 1 0 1 1 1 1 1 1 0 0 1 0 0 0 0]


In [46]:
print(y_test)

[0 1 0 1 1 1 0 1 1 1 1 1 1 0 0 0 0 0 0 0]


In [47]:
score = logisticRegr.score(x_test, y_test)
print(score)

0.9


In [52]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(logisticRegr,x_test,y_test,cv=10,scoring='r2')
print(scores)
print(scores.mean())
print(scores.std())
print()

scores_predict = cross_val_score(logisticRegr,x_test,y_test_model_pred,cv=10,scoring='r2')
print(scores_predict)
print(scores_predict.mean())
print(scores_predict.std())

[ 1. -1.  1.  1.  1. -1.  1.  1.  1.  1.]
0.6
0.8000000000000002

[ 1.  1.  1.  1.  1.  1.  1.  1.  1. -1.]
0.8
0.6


In [53]:
from sklearn import metrics  
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_test_model_pred ))  
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_test_model_pred ))  
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_test_model_pred ))) 

Mean Absolute Error: 0.1
Mean Squared Error: 0.1
Root Mean Squared Error: 0.31622776601683794
